import sys
import os
from krita import *

# API Listing: https://github.com/scottpetrovic/krita-python-auto-complete/blob/master/output/PyKrita.py
def link_external_packages():
    # get the path to the pykrita directory located in the Resource Directory
    resource_dir = str(Krita.instance().readSetting("", "ResourceDirectory", ""))
    pykrita_resource_dir =  os.path.join(resource_dir, "pykrita")
    lib_file_path = os.path.join(pykrita_resource_dir, "my_extension/lib")

    # fetch the dependecy path that was generated in the .lib file generated by our build script
    with open(lib_file_path, "r") as f:
        dep_path = os.path.join(pykrita_resource_dir, f.readline()[:-1])

    # set the path if not already set
    if dep_path not in sys.path:
        sys.path.append(dep_path)

# THIS NEEDS TO BE CALLED BEFORE WE CAN PERFORM ANY OPERATIONS WITH EXTERNAL LIBRARIES 
link_external_packages()

from PyQt5.QtWidgets import *
import numpy as np
import cv2
from PIL import Image

class MyExtension(DockWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("My Extension")
        main_widget = QWidget(self)
        self.setWidget(main_widget)

        # btn_alert = QPushButton("do something else!", main_widget)
        # btn_alert.clicked.connect(self.popup)

        btn_alter_img = QPushButton("Change the image!", main_widget)
        btn_alter_img.clicked.connect(self.convert2cv2)

        main_widget.setLayout(QVBoxLayout())
        main_widget.layout().addWidget(btn_alter_img)

    def canvasChanged(self, canvas):
        pass

    def popup(self):
        QMessageBox.information(QWidget(), "My Extension Popup", "Numpy Version: {}".format(cv2.__version__))

    def convert2cv2(self):
        active_doc = Krita.instance().activeDocument()
        layer = active_doc.activeNode()
        width = active_doc.width()
        height = active_doc.height()

        pixel_data = layer.pixelData(0, 0, width, height)
        
        mode = "RGBA"
        size = (width, height)
        pil_img = Image.frombytes(mode, size, pixel_data)

        numpy_img = np.array(pil_img, dtype=np.uint8)

        red, blk_wht_img = cv2.threshold(numpy_img, 128, 255, cv2.THRESH_BINARY)
        result_image = Image.fromarray(blk_wht_img, mode)

        result_pixel_data = result_image.tobytes()

        layer.setPixelData(result_pixel_data, 0, 0, width, height)

        active_doc.refreshProjection()



# And add the extension to Krita's list of extensions:
Krita.instance().addDockWidgetFactory(DockWidgetFactory(
    "My Extension", DockWidgetFactoryBase.DockRight, MyExtension))

